export const paperImages = {
  "Interactive Information Visualization of a Million Items": "./src/thumbnails/Interactive_Information_Visualization_of_a_Million_Items.png",
  "Constant density visualizations of non-uniform distributions of data": "./src/thumbnails/Constant_density_visualizations_of_non-uniform_distributions_of_data.png",
  "Mobile Liquid 2D Scatter Space (ML2DSS)": "./src/thumbnails/Mobile_Liquid_2D_Scatter_Space_ML2DSS.png",
  "Kyrix-S: Authoring Scalable Scatterplot Visualizations of Big Data": "./src/thumbnails/Kyrix-S_Authoring_Scalable_Scatterplot_Visualizations_of_Big_Data.png",
  "Using Animation to Alleviate Overdraw in Multiclass Scatterplot Matrices": "./src/thumbnails/Using_Animation_to_Alleviate_Overdraw_in_Multiclass_Scatterplot_Matrices.png",
  "Prediction of data visibility in two-dimensional scatterplots": "./src/thumbnails/Prediction_of_data_visibility_in_two-dimensional_scatterplots.png",
  "Plotting Symbols: Choose distinct symbols that overlap without ambiguity and communicate relationships in data.": "./src/thumbnails/Plotting_Symbols_Choose_distinct_symbols_that_overlap_without_ambiguity_and_comm.png",
  "Towards Perceptual Optimization of the Visual Design of Scatterplots": "./src/thumbnails/Towards_Perceptual_Optimization_of_the_Visual_Design_of_Scatterplots.png",
  "Alpha, contrast and the perception of visual metadata": "./src/thumbnails/Alpha_contrast_and_the_perception_of_visual_metadata.png",
  "Dynamic opacity optimization for scatter plots": "./src/thumbnails/Dynamic_opacity_optimization_for_scatter_plots.png",
  "Optimizing Color Assignment for Perception of Class Separability in Multiclass Scatterplots": "./src/thumbnails/Optimizing_Color_Assignment_for_Perception_of_Class_Separability_in_Multiclass_S.png",
  "A Model of Symbol Size Discrimination in Scatterplots": "./src/thumbnails/A_Model_of_Symbol_Size_Discrimination_in_Scatterplots.png",
  "Sunsplot plots: Model-based structure Enhancement for Dense Scatterplot": "./src/thumbnails/Sunsplot_plots_Model-based_structure_Enhancement_for_Dense_Scatterplot.png",
  "Fast Interactive Design of Scatterplots for Large Data Set Visualisation": "./src/thumbnails/Fast_Interactive_Design_of_Scatterplots_for_Large_Data_Set_Visualisation.png",
  "Guaranteed Visibility in Scatterplots with Tolerance": "./src/thumbnails/Guaranteed_Visibility_in_Scatterplots_with_Tolerance.png",
  "Enhancing Scatterplots with Multi-Dimensional Focal Blur": "./src/thumbnails/Enhancing_Scatterplots_with_Multi-Dimensional_Focal_Blur.png",
  "Interactive Focus+Context Visualization with Linked 2D/3D Scatterplots": "./src/thumbnails/Interactive_FocusContext_Visualization_with_Linked_2D3D_Scatterplots.png",
  "Dual Space Coupling Model Guided Overlap-Free Scatterplot": "./src/thumbnails/Dual_Space_Coupling_Model_Guided_Overlap-Free_Scatterplot.png",
  "VizCluster and Its Application on Clustering Gene Expression Data": "./src/thumbnails/VizCluster_and_Its_Application_on_Clustering_Gene_Expression_Data.png",
  "Generalized scatter plots": "./src/thumbnails/Generalized_scatter_plots.png",
  "Brushing of Attribute Clouds for the Visualization of Multivariate Data": "./src/thumbnails/Brushing_of_Attribute_Clouds_for_the_Visualization_of_Multivariate_Data.png",
  "De-cluttering Scatterplots with Integral Images": "./src/thumbnails/De-cluttering_Scatterplots_with_Integral_Images.png",
  "Blue Noise Plots": "./src/thumbnails/Blue_Noise_Plots.png",
  "Designing pixel-oriented visualization techniques: theory and applications": "./src/thumbnails/Designing_pixel-oriented_visualization_techniques_theory_and_applications.png",
  "Intelligently Resolving Point Occlusion": "./src/thumbnails/Intelligently_Resolving_Point_Occlusion.png",
  "Clutter Reduction in Multi-Dimensional Data Visualization Using Dimension Reordering": "./src/thumbnails/Clutter_Reduction_in_Multi-Dimensional_Data_Visualization_Using_Dimension_Reorde.png",
  "Evaluation of Sampling Methods for Scatterplots": "./src/thumbnails/Evaluation_of_Sampling_Methods_for_Scatterplots.png",
  "Multi-class blue noise sampling": "./src/thumbnails/Multi-class_blue_noise_sampling.png",
  "The sampling lens: making sense of saturated visualisations": "./src/thumbnails/The_sampling_lens_making_sense_of_saturated_visualisations.png",
  "By chance enhancing interaction with large data sets through statistical sampling": "./src/thumbnails/By_chance_enhancing_interaction_with_large_data_sets_through_statistical_samplin.png",
  "Automatic Scatterplot Design Optimization for Clustering Identification": "./src/thumbnails/Automatic_Scatterplot_Design_Optimization_for_Clustering_Identification.png",
  "Visual-assisted Outlier Preservation for Scatterplot Sampling": "./src/thumbnails/Visual-assisted_Outlier_Preservation_for_Scatterplot_Sampling.png",
  "Density control through random sampling: an architectural perspective": "./src/thumbnails/Density_control_through_random_sampling_an_architectural_perspective.png",
  "A Recursive Subdivision Technique for Sampling Multi-class Scatterplots": "./src/thumbnails/A_Recursive_Subdivision_Technique_for_Sampling_Multi-class_Scatterplots.png",
  "Density biased sampling: An improved method for data mining and clustering": "./src/thumbnails/Density_biased_sampling_An_improved_method_for_data_mining_and_clustering.png",
  "Pyramid-based Scatterplots Sampling for Progressive and Streaming Data Visualization": "./src/thumbnails/Pyramid-based_Scatterplots_Sampling_for_Progressive_and_Streaming_Data_Visualiza.png",
  "Data Sampling in Multi-view and Multi-class Scatterplots via Set Cover Optimization": "./src/thumbnails/Data_Sampling_in_Multi-view_and_Multi-class_Scatterplots_via_Set_Cover_Optimizat.png",
  "Give chance a chance: modeling density to enhance scatter plot quality through random data sampling": "./src/thumbnails/Give_chance_a_chance_modeling_density_to_enhance_scatter_plot_quality_through_ra.png",
  "Bin-summarise-smooth: A framework for visualising large data": "./src/thumbnails/Bin-summarise-smooth_A_framework_for_visualising_large_data.png",
  "Solutions to The problem of Over-plotting in Graphs (Visual Business Intelligence Newsletter)": "./src/thumbnails/Solutions_to_The_problem_of_Over-plotting_in_Graphs_Visual_Business_Intelligence.png",
  "A taxonomy of clutter reduction for information visualisation": "./src/thumbnails/A_taxonomy_of_clutter_reduction_for_information_visualisation.png",
  "Gatherplot: A Non-Overlapping Scatterplot": "./src/thumbnails/Gatherplot_A_Non-Overlapping_Scatterplot.png",
  "Visual abstraction and exploration of multi-class scatterplots": "./src/thumbnails/Visual_abstraction_and_exploration_of_multi-class_scatterplots.png",
  "PixelatedScatter: Arbitrary-level Visual Abstraction for Large-scale Multiclass Scatterplots": "./src/thumbnails/PixelatedScatter_Arbitrary-level_Visual_Abstraction_for_Large-scale_Multiclass_S.png",
  "By chance is not enough: preserving relative density through nonuniform sampling": "./src/thumbnails/By_chance_is_not_enough_preserving_relative_density_through_nonuniform_sampling.png",
  "Overplotting: Unified solutions under Abstract Rendering": "./src/thumbnails/Overplotting_Unified_solutions_under_Abstract_Rendering.png",
  "Scatterplot Matrix Technique for Large N": "./src/thumbnails/Scatterplot_Matrix_Technique_for_Large_N.png",
  "OM4AnI: A Novel Overlap Measure for Anomaly Identification in Multi-Class Scatterplots": "./src/thumbnails/OM4AnI_A_Novel_Overlap_Measure_for_Anomaly_Identification_in_Multi-Class_Scatter.png",
  "Stacking Graphic Elements to Avoid Over-Plotting": "./src/thumbnails/Stacking_Graphic_Elements_to_Avoid_Over-Plotting.png",
  "Splatterplots: Overcoming overdraw in scatter plots": "./src/thumbnails/Splatterplots_Overcoming_overdraw_in_scatter_plots.png",
  "A Declarative Rendering Model for Multiclass Density Maps": "./src/thumbnails/A_Declarative_Rendering_Model_for_Multiclass_Density_Maps.png",
  "A new weaving technique for handling overlapping regions": "./src/thumbnails/A_new_weaving_technique_for_handling_overlapping_regions.png",
  "StreamMap: Smooth Dynamic Visualization of High-Density Streaming Points": "./src/thumbnails/StreamMap_Smooth_Dynamic_Visualization_of_High-Density_Streaming_Points.png",
  "AgentVis: Visual Analysis of Agent Behavior With Hierarchical Glyphs": "./src/thumbnails/AgentVis_Visual_Analysis_of_Agent_Behavior_With_Hierarchical_Glyphs.png",
  "Sca2Gri: Scalable Gridified Scatterplots": "./src/thumbnails/Sca2Gri_Scalable_Gridified_Scatterplots.png",
  "Visualizing Data Using T-SNE": "./src/thumbnails/Visualizing_Data_Using_T-SNE.png",
  "A grid-based method for removing overlaps of dimensionality reduction scatterplot layouts.": "./src/thumbnails/A_grid-based_method_for_removing_overlaps_of_dimensionality_reduction_scatterplo.png",
  "Cluster-Based Visual Abstraction for Multivariate Scatterplots": "./src/thumbnails/Cluster-Based_Visual_Abstraction_for_Multivariate_Scatterplots.png",
  "A taxonomy of visual cluster separation factors": "./src/thumbnails/A_taxonomy_of_visual_cluster_separation_factors.png",
  "Using Sunflower Metaphor to Reduce Clutter of Scatterplot": "./src/thumbnails/Using_Sunflower_Metaphor_to_Reduce_Clutter_of_Scatterplot.png",
  "Relaxing Dense Scatter Plots with Pixel-based Mappings": "./src/thumbnails/Relaxing_Dense_Scatter_Plots_with_Pixel-based_Mappings.png",
  "Improving 2D scatterplots effectiveness through sampling, displacement, and user perception": "./src/thumbnails/Improving_2D_scatterplots_effectiveness_through_sampling,_displacement,_and_user_perception.png",
  "Sampling techniques to improve big data exploration": "./src/thumbnails/Sampling_techniques_to_improve_big_data_exploration.png",
  "Hierarchical Aggregation for Information Visualization: Overview, Techniques, and Design Guidelines": "./src/thumbnails/Hierarchical_Aggregation_for_Information_Visualization:_Overview,_Techniques,_and_Design_Guidelines.png"
};